server:
  port: 8090

# jsp?????
  servlet:
    jsp:
      init-parameters:
        development: true


# datasource ??
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/data_demo?useSSL=false&useUnicode=true&characterEncode=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

    # jsp ??
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
